# Conexión PostgreSQL Render
spring.datasource.url=jdbc:postgresql://dpg-d6uo77q4d50c73f9a7t0-a.oregon-postgres.render.com:5432/apipedidos_1ga3
spring.datasource.username=apipadidos_user
spring.datasource.password=lGey1K4qQLVQn0YuB9G13gmK0HOR3i9f
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Puerto local de la aplicación
server.port=8081